version: '3.1'

services:
  securesql:
    build: ./sql
    image: securesql:latest
    environment:
      MYSQL_ROOT_PASSWORD: example
    networks:
      - dbnet
  secureapache:
    build: ./csrf
    image: secureapache
    networks:
      - lsio
      - dbnet
    ports:
       - "8003:80"

  # unsecureapache:
  #   build: ./nocsrf
  #   image: secureapache
  #   networks:
  #     - lsio
  #     - dbnet
  #   ports:
  #      - "8004:80"

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - "8005:80"
    networks:
      - lsio
      - dbnet
    links:
      - "securesql:db"

networks:
  lsio:
    external: true
  dbnet:

