version: '3.1'

services:
  pachedb:
    image: apachesql
    environment:
      MYSQL_ROOT_PASSWORD: example
      networks:
        -lsio
  phpmyadmin:
    image: phpmyadmin
    restart: always
    networks:
      - lsio
    links:
      - "pachedb:db"
networks:
  lsio:
    external: true

