version: '3.1'

services:
  pachedb:
    image: apachesql
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 9001:80
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 9002:80
    links:
      - "pachedb:db"
